image:
  - Visual Studio 2019

platform:
  - Any CPU

before_build:
  - nuget restore src
  # This is a hack, the dynamic generated fbs.generated files are not triggering at the right time for the build. This forces them to run before the build.
  # We force a build and return success code
  - ps: |
      $cmd = 'dotnet build src\FlatSharp.sln'
      iex "& $cmd"
      $host.SetShouldExit(0)
configuration:
  - Release

build:
  project: src\FlatSharp.sln

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:

artifacts:
  - path: '**\*'
    name: src
    type: zip

on_failure:
  - 7z a failure.zip *.* -xr!bin -xr!obj -r
  - appveyor PushArtifact failure.zip    