image:
  - Visual Studio 2019

platform:
  - Any CPU

before_build:
  - nuget restore src

configuration:
  - Release

build:
  project: src\FlatSharp.sln
  verbosity: detailed

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:

artifacts:
  - path: '**\*'
    name: src
    type: zip

on_failure:
  - 7z a failure.zip *.*
  - appveyor PushArtifact failure.zip
  